lint:
  files_exist:
    - assets/multiqc_config.yml
    - assets/nf-core-insdcdownload_logo_light.png
    - conf/igenomes.config
    - docs/images/nf-core-insdcdownload_logo_light.png
    - docs/images/nf-core-insdcdownload_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  files_unchanged:
    - LICENSE
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/workflows/linting.yml
    - assets/sendmail_template.txt
    - lib/NfcoreTemplate.groovy
    - .github/workflows/branch.yml
  nextflow_config:
    - manifest.name
    - manifest.homePage
nf_core_version: 2.8.0
repository_type: pipeline
template:
  author: "@muffato"
  description: Pipeline that downloads assemblies from INSDC into a Tree of Life directory structure
  force: false
  is_nfcore: false
  name: insdcdownload
  org: sanger-tol
  outdir: .
  skip_features:
    - igenomes
    - multiqc
    - fastqc
  version: 2.0.2
