contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #insdcdownload channel"
    url: https://nfcore.slack.com/channels/insdcdownload
    about: Discussion about the nf-core/insdcdownload pipeline
